### PR TITLE
cpu: aarch64: missing include for arm_compute::Scheduler

### PR DESCRIPTION
**Pull request by aletru01**
# Description

error: 'arm_compute::Scheduler' has not been declared
There is a missing include which leads to a compilation error

The issue shows up in testing with the Compute Library master, so it is
currently working with the 21.02 release, as used in the CI,
see: https://github.com/oneapi-src/oneDNN/blob/ca6ca816faa92025a231f3ff1d110b73c5a460c1/.github/automation/build_acl.sh#L21

However, this change is required to support builds from the tip of the Compute Library master, and future releases.

# Checklist

## General

- [X] Do all unit and benchdnn tests (`make test` and `make test_benchdnn_*`) pass locally for each commit?
- [X] Have you formatted the code using clang-format?

### New features

- [N/A] Have you added relevant tests?

- [N/A] Have you provided motivation for adding a new feature?

###Bug fixes

- [N/A] Have you added relevant regression tests?

- [N/A] Have you included information on how to reproduce the issue (either in a github issue or in this PR)?

### CODE REVIEW

**Comment by LukeIreland1** [comment]
Just adding an example of the error for a bit of background in case anyone is equally as confused as us, as to why this error only recently appeared (I still don't know)

```
#16 46.36 In file included from /home/ubuntu/packages/oneDNN/src/cpu/aarch64/acl_indirect_gemm_convolution.cpp:17:
#16 46.36 /home/ubuntu/packages/oneDNN/src/cpu/aarch64/acl_indirect_gemm_convolution.hpp: In member function 'dnnl::impl::status_t dnnl::impl::cpu::aarch64::acl_indirect_gemm_convolution_fwd_t::pd_t::init(dnnl::impl::engine_t*)':
#16 46.36 /home/ubuntu/packages/oneDNN/src/cpu/aarch64/acl_indirect_gemm_convolution.hpp:108:26: error: 'arm_compute::Scheduler' has not been declared
#16 46.36   108 |             arm_compute::Scheduler::get().set_num_threads(
#16 46.36       |                          ^~~~~~~~~
#16 48.21 src/cpu/aarch64/CMakeFiles/dnnl_cpu_aarch64.dir/build.make:110: recipe for target 'src/cpu/aarch64/CMakeFiles/dnnl_cpu_aarch64.dir/acl_indirect_gemm_convolution.cpp.o' failed
```

**Comment by igorsafo** [comment]
Hi @aletru01 and @LukeIreland1 Thank you for your PR. Just curious is the same compiler used for building both v21.02 and latest master?

Regards,
Igor Safonov

**Review by igorsafo — APPROVED** [review]

**Comment by LukeIreland1** [comment]
@igorsafo Internal pipelines within ONCPUML@Arm always build ACL with GCC 10, and for one pipeline, all but one of the branches using ACL fail, the none-failing one being oneDNN v2.1. This pipeline always builds with ACL master.

The other pipeline builds with both master and release (v21.02) versions of ACL, and only shows failure for branches using  ACL master.

I can't see which compiler is used in the Drone CI, but I don't see anything to suggest they will differ, so it's probably GCC 10 there too.

**Comment by nSircombe** [comment]
For the GCC stages in the DroneCI it should be using the 'default' GCC throughout - I believe that's 4.5 for Ubuntu 16 and 7.4 for Ubuntu 18?
For the Clang stages, it should be using using Clang-9 throughout.
This issue wouldn't show up in the DroneCI pipelines until the next Compute Library release, as far as I can tell. That will include some recent changes to the Scheduler, which are currently present on master (...and I assume the root cause of the issue, although it's not entirely obvious that the changes would be a problem! Nevertheless, this does resolve it).

**Comment by igorsafo** [comment]
@aletru01 Thank you for your contribution!
