### PR TITLE
xe: jit: ocl: add missing double loads

### PR DESCRIPTION
**Pull request by rjoursler**
Fixes some compilation errors when loading data from post-op buffers introduced by #3558.

### CODE REVIEW

**Review by atkassen — APPROVED** [review]

**Comment by rjoursler** [comment]
make test
disable test_device_cpu
