### ISSUE TITLE
Test `wino_conv_test_t.TestLargePadding` of 2.6.2 fails on aarch64 with Arm Compute Library 22.08

### ISSUE THREAD

**Issue by ggardet** [oneapi-src/oneDNN#1460]
# Summary
```
[ 7748s] 57/98 Test #61: test_iface_wino_convolution ......................***Failed    0.68 sec
[ 7748s] Note: Google Test filter = *:-*_GPU*
[ 7748s] [==========] Running 3 tests from 1 test suite.
[ 7748s] [----------] Global test environment set-up.
[ 7748s] [----------] 3 tests from wino_conv_test_t
[ 7748s] [ RUN      ] wino_conv_test_t.TestSmallPadding
[ 7748s] [       OK ] wino_conv_test_t.TestSmallPadding (79 ms)
[ 7748s] [ RUN      ] wino_conv_test_t.TestLargePadding
[ 7748s] /home/abuild/rpmbuild/BUILD/oneDNN-2.6.2/tests/gtests/test_iface_wino_convolution.cpp:147: Failure
[ 7748s] Expected: convolution_forward::primitive_desc(fwd_op_desc, eng) throws an exception.
[ 7748s]   Actual: it doesn't.
[ 7748s] [  FAILED  ] wino_conv_test_t.TestLargePadding (0 ms)
[ 7748s] [ RUN      ] wino_conv_test_t.TestUnsupportedKernel
[ 7748s] [       OK ] wino_conv_test_t.TestUnsupportedKernel (0 ms)
[ 7748s] [----------] 3 tests from wino_conv_test_t (103 ms total)
[ 7748s] 
[ 7748s] [----------] Global test environment tear-down
[ 7748s] [==========] 3 tests from 1 test suite ran. (105 ms total)
[ 7748s] [  PASSED  ] 2 tests.
[ 7748s] [  FAILED  ] 1 test, listed below:
[ 7748s] [  FAILED  ] wino_conv_test_t.TestLargePadding
[ 7748s] 
[ 7748s]  1 FAILED TEST
```

# Version
OneDNN 2.6.2

# Environment
Tested on openSUSE Tumbleweed aarch64 build system.

# Steps to reproduce
Try to run tests for openSUSE Tumbleweed aarch64.

# Observed behavior
`wino_conv_test_t.TestLargePadding` fails.

# Expected behavior
`wino_conv_test_t.TestLargePadding` should pass.

**Comment by nSircombe** [comment]
Hi @ggardet,

This issue should be resolved in the `HEAD` of `master` and the 2.7 release branch - https://github.com/oneapi-src/oneDNN/pull/1428

Alternatively, older versions of Compute Library should work with oneDNN 2.6.x, as they do not carry the changes to the ACL wino interface which lead to this error.

Could you confirm one of these solutions work for you?

**Comment by ggardet** [comment]
I backported #1428 but is seems it is not enough, since I now get the following build error:
```
[  399s] /home/abuild/rpmbuild/BUILD/oneDNN-2.6.2/src/cpu/aarch64/acl_convolution_utils.cpp:342:5: error: 'ACL_CHECK_SUPPORT' was not declared in this scope
[  399s]   342 |     ACL_CHECK_SUPPORT(!shape_ok, "shape not supported by winograd kernels");
[  399s]       |     ^~~~~~~~~~~~~~~~~
[  399s] make[2]: *** [src/cpu/aarch64/CMakeFiles/dnnl_cpu_aarch64.dir/build.make:93: src/cpu/aarch64/CMakeFiles/dnnl_cpu_aarch64.dir/acl_convolution_utils.cpp.o] Error 1
```

**Comment by nSircombe** [comment]
Hi @ggardet,

> I backported https://github.com/oneapi-src/oneDNN/pull/1428 but is seems it is not enough,

Indeed, the `ACL_CHECK_SUPPORT` macro post-dates the 2.6 release - https://github.com/oneapi-src/oneDNN/commit/fa93750bfb821fe05e3190b36f52b5bd88a57110

...so this would also need to be back ported. There may be further interdependent changes missing from the 2.6.x branch too.

I would recommend moving to `master` or the 2.7 RC, or moving back to ACL 22.05 - Is there anything which blocks you from taking one of these options?

**Comment by ggardet** [comment]
Backporting https://github.com/oneapi-src/oneDNN/commit/fa93750bfb821fe05e3190b36f52b5bd88a57110 in addition to #1428 seems enough. Thanks!

**Comment by nSircombe** [comment]
@ggardet 

> Backporting https://github.com/oneapi-src/oneDNN/commit/fa93750bfb821fe05e3190b36f52b5bd88a57110 in addition to https://github.com/oneapi-src/oneDNN/pull/1428 seems enough. Thanks! 

Ah, good, glad to hear it.
