### ISSUE TITLE
Help need: use graph API to construct a subgraph of multi-head attention

### ISSUE THREAD

**Issue by FuncJ** [oneapi-src/oneDNN#1740]
Dear Sir/Madam, I want to use oneDNN's graph API. It seems we can benefit from the graph API to accelerate the `multi-head attention` block. However, how can we construct a subgraph of multi-head attention and get the best performance on my machine? Any source code available? Thanks.

![image](https://github.com/oneapi-src/oneDNN/assets/51168944/0927d334-7a3a-4b15-b9f5-dfa0a41f41e2)
![image](https://github.com/oneapi-src/oneDNN/assets/51168944/429cae52-cb9b-4c25-8a5e-5b9c075b7d6f)

**Comment by vpirogov** [comment]
@FuncJ, using Graph API to implement MHA is not different from implementing any other graph. You can use [Graph API examples](https://github.com/oneapi-src/oneDNN/tree/master/examples/graph) as a starting point and [developer guide](https://oneapi-src.github.io/oneDNN/graph_extension.html) to figure out the rest.

+@taolv for additional comments.

**Comment by FuncJ** [comment]
**Build error**
When I use `-DONEDNN_EXPERIMENTAL_GRAPH_COMPILER_BACKEND=ON`, the compilation of the oneDNN project fails.
```
1) mkdir -p build
2) cd build
3) cmake .. -DCMAKE_INSTALL_PREFIX=/home/xx/lib/oneDNN-3.3 -DCMAKE_BUILD_TYPE=Release -DDNNL_LIBRARY_TYPE=STATIC -DONEDNN_EXPERIMENTAL_GRAPH_COMPILER_BACKEND=ON
4) cmake --build . --target install -- -j64
```
```
/home/xx/project/oneDNN/src/graph/backend/graph_compiler/core/src/runtime/target_machine.cpp:31:5: error: ‘__cpuid_count’ was not declared in this scope
     __cpuid_count(InfoType, v2, info[0], info[1], info[2], info[3]);
     ^~~~~~~~~~~~~
/home/xx/project/oneDNN/src/graph/backend/graph_compiler/core/src/runtime/target_machine.cpp:31:5: note: suggested alternative: ‘__pid_t’
     __cpuid_count(InfoType, v2, info[0], info[1], info[2], info[3]);
     ^~~~~~~~~~~~~
     __pid_t
```

**Comment by FuncJ** [comment]
> @FuncJ, using Graph API to implement MHA is not different from implementing any other graph. You can use [Graph API examples](https://github.com/oneapi-src/oneDNN/tree/master/examples/graph) as a starting point and [developer guide](https://oneapi-src.github.io/oneDNN/graph_extension.html) to figure out the rest.
> 
> +@TaoLv for additional comments.

Thank you very much for your help and advice. But I got an error while building the module related to graph compiler.

**Build error**
When I use `-DONEDNN_EXPERIMENTAL_GRAPH_COMPILER_BACKEND=ON`, the compilation of the oneDNN-3.3.1 project fails.
```
1) mkdir -p build
2) cd build
3) cmake .. -DCMAKE_INSTALL_PREFIX=/home/xx/lib/oneDNN-3.3 -DCMAKE_BUILD_TYPE=Release -DDNNL_LIBRARY_TYPE=STATIC -DONEDNN_EXPERIMENTAL_GRAPH_COMPILER_BACKEND=ON
4) cmake --build . --target install -- -j64
```
```
/home/xx/project/oneDNN/src/graph/backend/graph_compiler/core/src/runtime/target_machine.cpp:31:5: error: ‘__cpuid_count’ was not declared in this scope
     __cpuid_count(InfoType, v2, info[0], info[1], info[2], info[3]);
     ^~~~~~~~~~~~~
/home/xx/project/oneDNN/src/graph/backend/graph_compiler/core/src/runtime/target_machine.cpp:31:5: note: suggested alternative: ‘__pid_t’
     __cpuid_count(InfoType, v2, info[0], info[1], info[2], info[3]);
     ^~~~~~~~~~~~~
     __pid_t
```

**Comment by vpirogov** [comment]
Thanks for the report, @FuncJ. While we are looking at the issue you can use `-DDNNL_LIBRARY_TYPE=DYNAMIC` as a workaround.

**Comment by Menooker** [comment]
Hi @FuncJ , I cannot reproduce your build error. Which compiler and its version are you using while you find the build error? You can find which compiler `cmake` selects by the output of the `3)` step:

```
cmake .. -DCMAKE_INSTALL_PREFIX=/home/xx/lib/oneDNN-3.3 -DCMAKE_BUILD_TYPE=Release -DDNNL_LIBRARY_TYPE=STATIC -DONEDNN_EXPERIMENTAL_GRAPH_COMPILER_BACKEND=ON
```

Also, it would be very helpful if you could provide info about you operation system and CPU brand if it is OK to you. Thanks.

**Comment by FuncJ** [comment]
Sorry for the delayed feedback. When I compile oneDNN's graph compiler module on an ARM multi-core server, an error occurs, but not on an x86 server.

**Comment by FuncJ** [comment]
Thank you very much for your help.

**Comment by FuncJ** [comment]
When I compile with ACL 22.05 and oneDNN 3.2 on the aarch64 architecture, I encounter the following error message: acl_utils.hpp:96.22: error: "arm_compute::WeightFormat" has not been declared. Which versions of oneDNN and ACL should I use? Thanks.

> > Sorry for the delayed feedback. When I compile oneDNN's graph compiler module on an ARM multi-core server, an error occurs, but not on an x86 server.

**Comment by FuncJ** [comment]
no matching function for call to 'arm_compute::Con2dInfo::Conv2dInfo" when oneDNN 3.3.3 and ACL 23.11

**Comment by vpirogov** [comment]
oneDNN v3.2 requires ACL 23.05 or newer as documented in [system requirements](https://github.com/oneapi-src/oneDNN/tree/v3.2?tab=readme-ov-file#system-requirements).

Next time please open new issue for new questions or bug reports. This would help to get faster response.

**Comment by FuncJ** [comment]
> oneDNN v3.2 requires ACL 23.05 or newer as documented in [system requirements](https://github.com/oneapi-src/oneDNN/tree/v3.2?tab=readme-ov-file#system-requirements).
> 
> Next time please open new issue for new questions or bug reports. This would help to get faster response.

Thanks
